cache: false
language: node_js
node_js:
  - "0.12"

install:
  - npm install

before_script:
  - npm install -g grunt-cli bower
  - npm install
  - bower install
  - bundle install

script:
  - grunt build
  - grunt test

notifications:
  email:
    on_success: never
    on_failure: change
